### ISSUE TITLE
Are you kinda stupid?

### ISSUE THREAD

**Issue by AkumaNoTsubasa** [BlurSotong1/asking_for_help#1]
This is not a damn contact form. If you find my name here, you can find me on fucking twitter, PATHOFEXILE.COM THE GAME ITSELF and anywhere else. Why the fuck do you want to look like god damn stupid phishing bot that wants to do shady shit instead of entering my name into ANY community that either has something to do with poe or is about writing to each other
![opera_DSVo5E4KKM](https://github.com/user-attachments/assets/2aefb069-999e-4b64-8210-9661785363f8)
![opera_ffMBLIDAMv](https://github.com/user-attachments/assets/09b46d9f-1b9a-4138-9092-69174cd6c015)

would YOU accept any of this shit without any knowledge or waiting for this? NO you don't. Because only bad people do these invites to lure into bad shit.

Write me on a platform that is about writing. NOT gonna answer here. wtf is wrong with you brol

**Comment by BlurSotong1** [comment]
sorry i didnt know cus i am really new to this. I sincerely apologise.
